//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "machines")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub mac: String,
    pub name: Option<String>,
    pub status: String,
    pub last_seen_at: Option<DateTime>,
    pub approved_at: Option<DateTime>,
    pub installed_at: Option<DateTime>,
    pub install_started_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub os_version_id: Option<i64>,
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ssh_key: Option<String>,
    pub install_disk: Option<String>,
    pub cloudinit_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub packages: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub timezone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::os_versions::Entity",
        from = "Column::OsVersionId",
        to = "super::os_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    OsVersions,
}

impl Related<super::os_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OsVersions.def()
    }
}
