//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "os_versions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub version: String,
    pub arch: String,
    #[sea_orm(column_type = "Text")]
    pub kernel_url: String,
    #[sea_orm(column_type = "Text")]
    pub initrd_url: String,
    #[sea_orm(column_type = "Text")]
    pub iso_url: String,
    pub download_status: String,
    pub bytes_downloaded: i64,
    pub total_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub boot_mode: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::machines::Entity")]
    Machines,
}

impl Related<super::machines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Machines.def()
    }
}
