//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::machines::Entity as Machines;
pub use super::os_versions::Entity as OsVersions;
pub use super::settings::Entity as Settings;
pub use super::users::Entity as Users;
