// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params of the approve transition: pick the OS version to install.
 */
export type ApproveMachineParams = { os_version_id: bigint, };
