// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params of the create endpoint.
 */
export type CreateOsVersionParams = { name: string, version: string, arch: string, kernel_url: string, initrd_url: string, iso_url: string, boot_mode: "online" | "offline" | "nfs", };
