// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params of `POST /api/machines` — manual registration by MAC with an
 * optional install identity.
 */
export type CreateMachineParams = { mac: string, name: string | null, username: string | null, ssh_key: string | null, notes: string | null, install_disk: string | null, cloudinit_url: string | null, packages: string | null, timezone: string | null, 
/**
 * Write-only plaintext install password, hashed server-side.
 */
password: string | null, };
