// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire representation of a machine. Timestamps are RFC3339 strings.
 */
export type MachineResponse = { id: bigint, mac: string, name: string | null, username: string | null, ssh_key: string | null, status: string, os_version_id: bigint | null, last_seen_at: string | null, approved_at: string | null, install_started_at: string | null, installed_at: string | null, notes: string | null, install_disk: string | null, cloudinit_url: string | null, packages: string | null, timezone: string | null, 
/**
 * Whether the machine carries its own install password. The hash itself
 * is never exposed — the UI only distinguishes "own" from "global".
 */
password_set: boolean, };
