// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire representation of an OS version and its mirror-download progress.
 */
export type OsVersionResponse = { id: bigint, name: string, version: string, arch: string, kernel_url: string, initrd_url: string, iso_url: string, download_status: string, boot_mode: string, bytes_downloaded: number, total_bytes: number, error: string | null, };
