// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every known setting, with the model-level defaults already applied.
 */
export type SettingsResponse = { default_os_version_id: number | null, install_username: string, 
/**
 * Whether an install password has been set (the hash itself is never
 * exposed). Lets the UI distinguish "unset" from "leave blank to keep".
 */
install_password_set: boolean, ssh_key: string, timezone: string, 
/**
 * Default package list installed after the OS install, one per line.
 */
packages: string, 
/**
 * Default install disk pinned in the autoinstall storage config.
 */
install_disk: string | null, public_host: string | null, nfs_host: string | null, nfs_export_root: string | null, };
