// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params of `PUT /api/machines/:id` — edit the install identity.
 */
export type UpdateMachineParams = { name: string | null, username: string | null, ssh_key: string | null, notes: string | null, install_disk: string | null, cloudinit_url: string | null, packages: string | null, timezone: string | null, 
/**
 * Write-only plaintext install password, hashed server-side.
 */
password: string | null, 
/**
 * `true` clears the machine's own password (falls back to global).
 */
password_reset: boolean | null, };
