// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params of the update endpoint (all fields optional).
 */
export type UpdateOsVersionParams = { name: string | null, version: string | null, arch: string | null, kernel_url: string | null, initrd_url: string | null, iso_url: string | null, boot_mode: "online" | "offline" | "nfs" | null, };
