// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key/value map of settings to upsert. Only the known keys are accepted.
 */
export type UpdateSettingsParams = { values: { [key in string]: string }, };
